version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db